profile: full
excluded_packages:
  - api-portal.tanzu.vmware.com
  - image-policy-webhook.signing.apps.tanzu.vmware.com
  - learningcenter.tanzu.vmware.com
  - workshops.learningcenter.tanzu.vmware.com

buildservice:
  kp_default_repository: '<your_dockerhub_username>/tbs'
  kp_default_repository_username: '<your_dockerhub_username>'
  kp_default_repository_password: "<your_dockerhub_secret>"
  tanzunet_username: "<your_tanzunet_username>"
  tanzunet_password: "<your_tanzunet_password>"

supply_chain: basic
#supply_chain: testing_scanning

ootb_supply_chain_basic:
#ootb_supply_chain_basic_testing_scanning:
  service_account: default
  cluster_builder: default
  registry:
    server: 'index.docker.io'
    repository: '<your_dockerhub_username>'
  gitops:
    # Leave empty for public repos, add a secret for private repos.
    ssh_secret: "git-ssh"
    repository_prefix: git@github.com:pvdbleek/
    # The following parameters are optional:
    # username: ""
    # email: ""
    # branch: ""
    # commit_message: ""

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "192.168.64.6.nip.io" # Replace IP with your minikube IP
  app_config:
    app:
        baseUrl: http://tap-gui.192.168.64.6.nip.io # Replace IP with your minikube IP
    integrations:
      github: 
        - host: github.com
          token: <your_github_api_token>
    catalog:
      locations:
        - type: url
          # Replace with your own, or just use this one as a blank catalog.
          target: https://github.com/pvdbleek/tap-catalogs/blob/master/blank/catalog-info.yaml
    backend:
        baseUrl: http://tap-gui.192.168.64.6.nip.io # Replace IP with your minikube IP
        cors:
            origin: http://tap-gui.192.168.64.6.nip.io # Replace IP with your minikube IP

contour:
  envoy:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443

cnrs:
  provider: local
  domain_name: "192.168.64.6.nip.io" # Replace IP with your minikube IP

ceip_policy_disclosed: true

metadata_store:
  app_service_type: 'NodePort'

grype:
  namespace: "default" 
  targetImagePullSecret: "registry-credentials"